// src/app/(pages)/contact/page.tsx
'use client'

import { motion } from 'framer-motion'
import Image from 'next/image'
import Link from 'next/link'
import { Card } from '@/components/ui/Card'
import { SectionHeader } from '@/components/ui/SectionHeader'
import { SOCIAL_LINKS } from '@/lib/constants'
import {
  pageContainer,
  listContainer,
  listItem
} from '@/lib/animations'

export default function ContactPage() {
  return (
    <motion.section
      className="section flex flex-1 flex-col items-center py-10 md:py-14"
      initial="hidden"
      animate="show"
      variants={pageContainer}
    >
      <div className="w-full max-w-[800px] px-5 md:px-6">
        <SectionHeader
          title="contact"
          subtitle="best ways to reach me, and places I exist online"
          as="h1"
          size="lg"
          align="center"
          variant="gradient"
        />

        <motion.div className="mt-6" variants={listContainer}>
          <motion.div
            className="contact-grid grid grid-cols-1 sm:grid-cols-2 gap-4 md:gap-5"
            variants={listContainer}
          >
            {SOCIAL_LINKS.map((link) => (
              <motion.div key={link.name} variants={listItem}>
                <Link
                  href={link.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="block h-full group"
                >
                  <Card
                    variant="contact"
                    className="
                      p-5 md:p-6
                      flex items-center gap-4
                      min-h-[85px]
                      bg-elevated
                      border border-border
                      shadow-xl
                      transition-all duration-300
                    "
                  >
                    <div className="
                      flex-shrink-0 
                      w-12 h-12 
                      flex items-center justify-center
                      rounded-lg
                      transition-all duration-300
                    ">
                      <Image
                        src={link.icon}
                        alt=""
                        width={24}
                        height={24}
                      />
                    </div>

                    <div className="flex flex-col justify-center items-start h-full flex-1 min-w-0">
                      <span className="
                        text-base 
                        font-medium 
                        text-fg 
                        leading-tight 
                        tracking-tight 
                        truncate w-full
                        group-hover:text-accent
                        transition-colors duration-300
                      ">
                        {link.name}
                      </span>
                      <span className="
                        mt-1 
                        text-sm 
                        font-light 
                        text-fg/50
                        leading-tight 
                        tracking-[0.02em] 
                        truncate w-full
                        group-hover:opacity-90
                        transition-opacity duration-300
                      ">
                        {link.handle}
                      </span>
                    </div>

                    <motion.div
                      className="
                        opacity-100 sm:opacity-0 sm:group-hover:opacity-100
                        -translate-x-0 sm:-translate-x-2
                        transition-all duration-300
                      "
                      animate={{ x: [0, 2, 0] }}
                      transition={{ repeat: Infinity, duration: 1.5, ease: 'easeInOut' }}
                    >
                      <svg 
                        width="16" 
                        height="16" 
                        viewBox="0 0 16 16" 
                        fill="none" 
                        className="text-accent/60"
                      >
                        <path 
                          d="M4.5 11.5L11.5 4.5M11.5 4.5H5.5M11.5 4.5V10.5" 
                          stroke="currentColor" 
                          strokeWidth="1.5" 
                          strokeLinecap="round" 
                          strokeLinejoin="round"
                        />
                      </svg>
                    </motion.div>
                  </Card>
                </Link>
              </motion.div>
            ))}
          </motion.div>

          <motion.p
            className="
              text-center 
              mt-10 
              text-sm 
              text-fg/50 
              font-light 
              tracking-[0.02em]
              max-w-md 
              mx-auto
            "
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.5, duration: 0.6 }}
          >
            Feel free to reach out for collabs, questions, or just to say hi!
          </motion.p>
        </motion.div>
      </div>
    </motion.section>
  )
}

// src/routes/contact/+page.svelte
<section id="contact" class="section contact-section">
  <div class="section-content">
    <h2 class="section-title">contact</h2>
    <p class="contact-subtitle">
      best ways to reach me, and places I exist online
    </p>

    <div class="contact-grid">
      <a
        href="https://discord.com/users/444582693255249950"
        target="_blank"
        rel="noopener noreferrer"
        class="contact-card"
      >
        <img src="/icons/discord.svg" alt="" class="contact-icon" />
        <div class="contact-text">
          <span class="contact-name">Discord</span>
          <span class="contact-handle">@asteriau</span>
        </div>
      </a>

      <a
        href="https://t.me/obregia"
        target="_blank"
        rel="noopener noreferrer"
        class="contact-card"
      >
        <img src="/icons/telegram.svg" alt="" class="contact-icon" />
        <div class="contact-text">
          <span class="contact-name">Telegram</span>
          <span class="contact-handle">@obregia</span>
        </div>
      </a>

      <a
        href="https://github.com/asteriau"
        target="_blank"
        rel="noopener noreferrer"
        class="contact-card"
      >
        <img src="/icons/github.svg" alt="" class="contact-icon" />
        <div class="contact-text">
          <span class="contact-name">GitHub</span>
          <span class="contact-handle">@asteriau</span>
        </div>
      </a>

      <a
        href="https://steamcommunity.com/id/asteriau"
        target="_blank"
        rel="noopener noreferrer"
        class="contact-card"
      >
        <img src="/icons/steam.svg" alt="" class="contact-icon" />
        <div class="contact-text">
          <span class="contact-name">Steam</span>
          <span class="contact-handle">@asteriau</span>
        </div>
      </a>
    </div>
  </div>
</section>

<style>
.contact-section {
  padding-top: 80px;
}

.contact-subtitle {
  font-size: 0.95rem;
  opacity: 0.65;
  margin-bottom: 48px;
  line-height: 1.5;
  max-width: 420px;
}

.contact-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: 16px;
}

.contact-card {
  background: rgba(21, 21, 21, 0.6);
  border: 1px solid var(--color-border);
  border-radius: 14px;
  padding: 16px 18px;

  display: flex;
  align-items: center;
  gap: 14px;

  text-decoration: none;
  color: var(--color-fg);

  backdrop-filter: blur(12px);
  transition:
    border-color 0.3s ease,
    transform 0.25s ease,
    box-shadow 0.25s ease;

  min-height: 70px;
}

.contact-card:hover {
  border-color: color-mix(
    in srgb,
    var(--main-accent) 45%,
    var(--color-border)
  );
  transform: translateY(-2px);
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.25);
}

.contact-icon {
  width: 22px;
  height: 22px;
  flex-shrink: 0;
  opacity: 0.9;
}

.contact-text {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: flex-start;
  height: 100%;
  flex: 1;
  transition: transform 0.25s ease;
}

.contact-card:hover .contact-text {
  transform: translateX(2px);
}

.contact-name {
  font-size: 1rem;
  font-weight: 600;
  color: var(--main-accent);
  line-height: 1.25;
  letter-spacing: 0.01em;
}

.contact-handle {
  margin-top: 2px;
  font-size: 0.85rem;
  opacity: 0.55;
  line-height: 1.2;
  letter-spacing: 0.02em;
}

@media (max-width: 480px) {
  .contact-grid {
    grid-template-columns: 1fr;
  }

  .contact-card {
    padding: 14px 16px;
    min-height: 65px;
  }
}
</style>
