// src/app/(pages)/projects/page.tsx
'use client'

import { useEffect, useState } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { motion } from 'framer-motion'

import { GITHUB_REPOS } from '@/lib/constants'
import { fetchRepository } from '@/lib/api/github'
import { formatUpdated } from '@/lib/utils'
import type { Repository } from '@/types/github'
import { Card } from '@/components/ui/Card'
import { SectionHeader } from '@/components/ui/SectionHeader'
import { pageContainer, listContainer, listItem } from '@/lib/animations'

import colorsData from '@/lib/colors.json'

const colors = colorsData as Record<string, { color: string | null; url?: string }>

function getLanguageColor(language: string | null): string {
  if (!language) return '#ccc'
  return colors[language]?.color ?? '#ccc'
}

export default function ProjectsPage() {
  const [repositories, setRepositories] = useState<Repository[]>([])

  useEffect(() => {
    const loadRepos = async () => {
      const token = process.env.NEXT_PUBLIC_GITHUB_TOKEN
      const results = await Promise.all(
        GITHUB_REPOS.map((url) => fetchRepository(url, token))
      )
      setRepositories(results.filter((repo): repo is Repository => repo !== null))
    }

    loadRepos()
  }, [])

  return (
    <motion.section
      className="section flex flex-1 flex-col items-center py-10 md:py-14"
      initial="hidden"
      animate="show"
      variants={pageContainer}
    >
      <div className="w-full max-w-[1200px] px-5 md:px-6">
        <SectionHeader
          title="projects"
          subtitle="here are some of the projects i've made or contributed to"
          as="h1"
          size="lg"
          align="center"
          variant="gradient"
        />

        <motion.div className="mt-6" variants={listContainer}>
          <motion.div className="projects-grid grid grid-cols-1 md:grid-cols-2 gap-5 md:gap-6" variants={listContainer}>
            {repositories.map((repo) => (
              <motion.div key={repo.id} variants={listItem}>
                <Link
                  href={repo.html_url}
                  target="_blank"
                  rel="noopener noreferrer"
                  aria-label={`View ${repo.full_name} on GitHub`}
                  className="no-underline text-inherit block h-full group"
                >
                  <Card
                    variant="project"
                    className="
                      p-5 md:p-6 
                      h-full 
                      flex flex-col 
                      bg-elevated
                      border border-border
                      shadow-xl
                      transition-all duration-300
                      min-h-[160px]
                    "
                  >
                    <header className="project-header flex items-center gap-3 mb-4 relative">
                      <div
                        className="
                          relative 
                          w-8 h-8 
                          flex-shrink-0
                          rounded-full 
                          overflow-hidden
                          border border-border/50
                          group-hover:border-accent/30
                          transition-colors duration-300
                        "
                      >
                        <Image
                          src={`${repo.owner.avatar_url}?s=64`}
                          alt={repo.owner.login}
                          width={32}
                          height={32}
                          className="object-cover"
                        />
                      </div>

                      <div className="project-name flex gap-1.5 text-base leading-tight min-w-0 flex-1">
                        <span className="opacity-65 truncate group-hover:opacity-80 transition-opacity duration-300">
                          {repo.owner.login}
                        </span>
                        <span className="opacity-45 flex-shrink-0">/</span>
                        <span className="text-accent font-medium truncate group-hover:text-accent/90 transition-colors duration-300">
                          {repo.name}
                        </span>
                      </div>

                      <span className="
                        absolute 
                        right-0 
                        top-0.5 
                        opacity-35 
                        flex-shrink-0
                        transition-transform duration-300
                        group-hover:translate-x-1
                        group-hover:rotate-12
                        group-hover:opacity-70
                      ">
                        <svg
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth="2"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          className="w-4 h-4"
                        >
                          <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
                          <path d="M15 3h6v6" />
                          <path d="M10 14 21 3" />
                        </svg>
                      </span>
                    </header>

                    <p className="
                      project-description 
                      text-[0.95rem] 
                      leading-relaxed 
                      opacity-70 
                      mb-2
                      text-left 
                      line-clamp-2 
                      flex-1
                      group-hover:opacity-85
                      transition-opacity duration-300
                    ">
                      {repo.description || 'No description provided'}
                    </p>

                    <footer className="
                      project-stats 
                      flex 
                      justify-between 
                      items-center 
                      text-sm 
                      opacity-70 
                      mt-auto
                      group-hover:opacity-90
                      transition-opacity duration-300
                    ">
                      <span className="text-xs opacity-60 tracking-[0.2px]">
                        {formatUpdated(repo.updated_at)}
                      </span>

                      {repo.language && (
                        <div className="
                          language 
                          flex 
                          items-center 
                          gap-2 
                          text-sm
                          group-hover:opacity-100
                          transition-opacity duration-300
                        ">
                          <span
                            className="
                              w-2.5 
                              h-2.5 
                              rounded-full 
                              flex-shrink-0
                              shadow-sm
                            "
                            style={{ backgroundColor: getLanguageColor(repo.language) }}
                          />
                          <span className="opacity-80 text-xs">
                            {repo.language}
                          </span>
                        </div>
                      )}
                    </footer>
                  </Card>
                </Link>
              </motion.div>
            ))}
          </motion.div>
        </motion.div>
      </div>
    </motion.section>
  )
}

// src/routes/projects/+page.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import languageColors from "$lib/colors.json";

  const REPOSITORIES = [
    "https://api.github.com/repos/asteriau/asteria.cat",
    "https://api.github.com/repos/asteriau/Whimsy",
    "https://api.github.com/repos/asteriau/dotfiles"
  ];

  interface Repository {
    id: number;
    name: string;
    full_name: string;
    description: string | null;
    html_url: string;
    language: string | null;
    updated_at: string;
    owner: {
      login: string;
      avatar_url: string;
    };
  }

  let repositories: Repository[] = [];
  let isLoading = true;

  const getLanguageColor = (language: string | null) =>
    languageColors[language ?? ""]?.color ?? "#ccc";

  async function fetchRepo(url: string, headers: HeadersInit) {
    try {
      const res = await fetch(url, { headers });
      if (!res.ok) return null;
      return (await res.json()) as Repository;
    } catch {
      return null;
    }
  }

  function formatUpdated(date: string) {
    const diff = Date.now() - new Date(date).getTime();
    const days = Math.floor(diff / 86400000);

    if (days < 1) return "updated today";
    if (days === 1) return "updated yesterday";
    if (days < 30) return `updated ${days} days ago`;

    const months = Math.floor(days / 30);
    if (months < 12) return `updated ${months} month${months > 1 ? "s" : ""} ago`;

    const years = Math.floor(months / 12);
    return `updated ${years} year${years > 1 ? "s" : ""} ago`;
  }

  onMount(async () => {
    const token = import.meta.env.VITE_GITHUB_TOKEN;

    const headers: HeadersInit = {
      Accept: "application/vnd.github.v3+json",
      ...(token && { Authorization: `Bearer ${token}` })
    };

    const results = await Promise.all(
      REPOSITORIES.map(url => fetchRepo(url, headers))
    );

    repositories = results.filter(
      (repo): repo is Repository => repo !== null
    );

    isLoading = false;
  });
</script>

<section id="projects" class="section">
  <div class="section-content">
    <h2 class="section-title">projects</h2>
    <p class="hero-summary">
      here are some of the projects i've made or contributed to
    </p>

    {#if isLoading}
      <div class="loading">
        <div class="loading-spinner" />
        <p>loading repos..</p>
      </div>
    {:else if repositories.length === 0}
      <div class="empty">
        <p>no repos to display</p>
      </div>
    {:else}
      <div class="projects-grid">
        {#each repositories as repo (repo.id)}
          <a
            href={repo.html_url}
            target="_blank"
            rel="noopener noreferrer"
            class="project-card"
            aria-label={`View ${repo.full_name} on GitHub`}
          >
            <div class="project-card-inner">
              <header class="project-header">
                <img
                  src={`${repo.owner.avatar_url}?s=64`}
                  alt={repo.owner.login}
                  class="avatar"
                />

                <div class="project-name">
                  <span class="owner">{repo.owner.login}</span>
                  <span class="separator">/</span>
                  <span class="name">{repo.name}</span>
                </div>

                <span class="external-icon">
                  <svg
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  >
                    <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
                    <path d="M15 3h6v6" />
                    <path d="M10 14 21 3" />
                  </svg>
                </span>
              </header>

              <p class="project-description">
                {repo.description || "No description provided"}
              </p>

              <footer class="project-stats">
                <span class="updated">{formatUpdated(repo.updated_at)}</span>

                {#if repo.language}
                  <div
                    class="language"
                    style="--lang-color: {getLanguageColor(repo.language)}"
                  >
                    <span class="language-dot" />
                    {repo.language}
                  </div>
                {/if}
              </footer>
            </div>
          </a>
        {/each}
      </div>
    {/if}
  </div>
</section>

<style>
  .section {
    display: flex;
    justify-content: center;
    padding: 60px 40px;
  }

  .section-content {
    max-width: 1200px;
    width: 100%;
    text-align: center;
  }

  .section-title {
    color: var(--main-accent);
    font-size: var(--font-size-large);
    font-weight: normal;
    margin-bottom: 30px;
    text-shadow: var(--text-shadow);
  }

  .hero-summary {
    font-size: var(--font-size-small);
    margin-bottom: 40px;
    opacity: 0.8;
  }

  .projects-grid {
    display: grid;
    grid-template-columns: 1fr;
    gap: 28px;
  }

  .project-card {
    text-decoration: none;
    color: inherit;
  }

  .project-card-inner {
    padding: 24px 26px;
    background: rgba(21, 21, 21, 0.6);
    backdrop-filter: blur(12px);
    border: 1px solid var(--color-border);
    border-radius: 16px;
    transition: transform 0.3s ease, border-color 0.3s ease;
  }

  .project-card:hover .project-card-inner {
    transform: translateY(-2px);
    border-color: rgba(141, 163, 185, 0.25);
  }

  .project-header {
    display: flex;
    align-items: center;
    gap: 12px;
    margin-bottom: 14px;
    position: relative;
  }

  .avatar {
    width: 32px;
    height: 32px;
    border-radius: 50%;
    border: 1px solid var(--color-border);
  }

  .project-name {
    display: flex;
    gap: 6px;
    font-size: 1rem;
    line-height: 1.3;
  }

  .owner {
    opacity: 0.6;
  }

  .separator {
    opacity: 0.4;
  }

  .name {
    color: var(--main-accent);
    font-weight: 500;
  }

  .external-icon {
    position: absolute;
    right: 0;
    top: 2px;
    opacity: 0.3;
    transition: opacity 0.3s ease;
  }

  .project-card:hover .external-icon {
    opacity: 0.6;
  }

  .external-icon svg {
    width: 15px;
    height: 15px;
  }

  .project-description {
    font-size: 0.95rem;
    line-height: 1.7;
    opacity: 0.75;
    margin-bottom: 20px;
    text-align: left;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    overflow: hidden;
  }

  .project-stats {
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 0.85rem;
    opacity: 0.75;
  }

  .updated {
    font-size: 0.85rem;
    opacity: 0.55;
    letter-spacing: 0.2px;
    white-space: nowrap;
  }

  .project-card:hover .updated {
    opacity: 0.7;
  }

  .language {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 0.9rem;
  }

  .language-dot {
    width: 10px;
    height: 10px;
    border-radius: 50%;
    background: var(--lang-color);
  }

  @media (min-width: 768px) {
    .projects-grid {
      grid-template-columns: repeat(2, 1fr);
    }
  }

  @media (max-width: 480px) {
    .project-name {
      flex-direction: column;
      gap: 2px;
    }

    .separator {
      display: none;
    }
  }
</style>
